# URL ??? ??????????? ? ???? ??????
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase

# ??? ???????????? ? ??????
spring.datasource.username=myuser
spring.datasource.password=mypassword

# ??????? ??? PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# ????????? Hibernate ??? ?????? ? ????? ??????
spring.jpa.hibernate.ddl-auto=update        # ?????????????? ?????????? ????? ???? ??????
spring.jpa.show-sql=true                    # ????? SQL ???????? ? ???????
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect  # ??????? ??? PostgreSQL
